# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(737, 678)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 140, 181, 227))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.date_Edit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.date_Edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(12, 0, 0)))
        self.date_Edit.setCalendarPopup(False)
        self.date_Edit.setTimeSpec(QtCore.Qt.LocalTime)
        self.date_Edit.setObjectName("date_Edit")
        self.verticalLayout.addWidget(self.date_Edit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.DA_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.DA_text.setObjectName("DA_text")
        self.verticalLayout.addWidget(self.DA_text)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Date2_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Date2_text.setObjectName("Date2_text")
        self.verticalLayout.addWidget(self.Date2_text)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.Set_para_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Set_para_Button.setObjectName("Set_para_Button")
        self.verticalLayout.addWidget(self.Set_para_Button)
        self.Show_pic_label = QtWidgets.QLabel(Form)
        self.Show_pic_label.setGeometry(QtCore.QRect(210, 20, 491, 611))
        self.Show_pic_label.setText("")
        self.Show_pic_label.setScaledContents(False)
        self.Show_pic_label.setObjectName("Show_pic_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 181, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.mendian_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.mendian_select.setObjectName("mendian_select")
        self.verticalLayout_2.addWidget(self.mendian_select)
        self.moban_select = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.moban_select.setObjectName("moban_select")
        self.verticalLayout_2.addWidget(self.moban_select)
        self.moban_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.moban_Button.setObjectName("moban_Button")
        self.verticalLayout_2.addWidget(self.moban_Button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "时间"))
        self.date_Edit.setDisplayFormat(_translate("Form", "yyyy-MM-dd HH:mm:ss"))
        self.label.setText(_translate("Form", "DA号"))
        self.DA_text.setText(_translate("Form", "1558924"))
        self.label_3.setText(_translate("Form", "日期"))
        self.Date2_text.setText(_translate("Form", "20201216"))
        self.label_4.setText(_translate("Form", "OMS单号"))
        self.lineEdit_3.setText(_translate("Form", "00215187506902"))
        self.Set_para_Button.setText(_translate("Form", "设置参数"))
        self.label_5.setText(_translate("Form", "选择模板"))
        self.moban_Button.setText(_translate("Form", "选择完成"))
